### ISSUE TITLE
Examples of array query params should not use commas

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cc-api-v3-style-guide#6] opened 2015-08-04 23:53 UTC
`param[]=value,param[]=value2` should be `param[]=value&param[]=value2`

Confirm that we are actually using the correct syntax in Cloud Controller.

**Comment by Gerg** [comment] 2015-08-17 06:16
Duplicate of #12

**Closed as completed by Gerg** 2015-08-17 06:16 UTC
