### ISSUE TITLE
Relationships/ Includes for collections

### ISSUE THREAD

**Issue by Gerg** [cloudfoundry/cc-api-v3-style-guide#37] opened 2015-08-21 21:51 UTC
How do they work?

**Comment by dieucao** [comment] 2015-09-15 17:06
@Gerg is this really a duplicate of: https://github.com/cloudfoundry/cc-api-v3-style-guide/issues/35?

**Comment by dieucao** [comment] 2015-10-08 18:24
Closing as a duplicate

**Closed as completed by dieucao** 2015-10-08 18:24 UTC
