### ISSUE TITLE
"Fields" query params should be normal arrays

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cc-api-v3-style-guide#8] opened 2015-08-05 00:24 UTC
When requesting partial resources, I expect to provide the normal array syntax. For example, `GET /resource?fields=guid,name` should be `GET /resource?fields[]=guid&fields[]=name`.

Otherwise, CC consumers will have to write code to serialize arrays in two different ways, depending on which array is being serialized.

**Comment by Gerg** [comment] 2015-08-17 06:16
Duplicate of #12

**Closed as completed by Gerg** 2015-08-17 06:16 UTC
