### ISSUE TITLE
"Including Related Resources" query params should be normal arrays

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cc-api-v3-style-guide#7] opened 2015-08-05 00:22 UTC
`included=foo,bar,bar.baz` should be `included[]=foo&included[]=bar&included[]=bar.baz` to match other array parameters.

**Comment by utako** [comment] 2015-08-05 21:01
+1

**Comment by Gerg** [comment] 2015-08-17 06:16
Duplicate of #12

**Closed as completed by Gerg** 2015-08-17 06:16 UTC
