### ISSUE TITLE
consider collapsing included resources

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/cc-api-v3-style-guide#45] opened 2015-09-02 21:32 UTC
currently if the same resource if referenced by a lot of items when relationships are inlined, we will repeat that resource throughout the response.

one of the patterns used to avoid this duplication is to use referenced and pull out all resources at one level. wdyt?

**Comment by zrob** [comment] 2015-09-03 01:16
this is exactly what we proposed.  we just hadn't worked out how to map the de-duped resources to all the things that they might be related to yet

**Comment by dieucao** [comment] 2015-09-15 17:05
Closing as a duplicate of: https://github.com/cloudfoundry/cc-api-v3-style-guide/issues/35

**Closed as completed by dieucao** 2015-09-15 17:05 UTC
